services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/james-freec/metabase-render.git # optional
    region: singapore
    plan: starter # ensure that metabase has at least 2GB of RAM (defaults to starter)
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: elephant
          property: connectionString
databases:
  - name: elephant
    databaseName: metabasedb
    region: singapore
    plan: free
    ipAllowList: [] # only allow internal connections