services:
  - type: web
    name: web-report-freec
    env: docker
    repo: https://github.com/james-freec/metabase-render.git # optional
    region: singapore
    plan: free # ensure that metabase has at least 2GB of RAM (defaults to starter)
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: db-metabase-freec
          property: connectionString
databases:
  - name: db-metabase-freec
    databaseName: metabasedb
    region: singapore
    plan: free
    ipAllowList: [] # only allow internal connections